## Clock signal
set_property PACKAGE_PIN E3 [get_ports Clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports Clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports Clk]

## LEDs
set_property PACKAGE_PIN T8 [get_ports {Led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[0]}]
set_property PACKAGE_PIN V9 [get_ports {Led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[1]}]
set_property PACKAGE_PIN R8 [get_ports {Led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[2]}]
set_property PACKAGE_PIN T6 [get_ports {Led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[3]}]
set_property PACKAGE_PIN T5 [get_ports {Led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[4]}]
set_property PACKAGE_PIN T4 [get_ports {Led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[5]}]
set_property PACKAGE_PIN U7 [get_ports {Led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[6]}]
set_property PACKAGE_PIN U6 [get_ports {Led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[7]}]
set_property PACKAGE_PIN V4 [get_ports {Led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[8]}]
set_property PACKAGE_PIN U3 [get_ports {Led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[9]}]
set_property PACKAGE_PIN V1 [get_ports {Led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[10]}]
set_property PACKAGE_PIN R1 [get_ports {Led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[11]}]
set_property PACKAGE_PIN P5 [get_ports {Led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[12]}]
set_property PACKAGE_PIN U1 [get_ports {Led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[13]}]
set_property PACKAGE_PIN R2 [get_ports {Led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[14]}]
set_property PACKAGE_PIN P2 [get_ports {Led[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Led[15]}]

##7 segment display
set_property PACKAGE_PIN L3 [get_ports {Segment[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[0]}]
set_property PACKAGE_PIN N1 [get_ports {Segment[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[1]}]
set_property PACKAGE_PIN L5 [get_ports {Segment[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[2]}]
set_property PACKAGE_PIN L4 [get_ports {Segment[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[3]}]
set_property PACKAGE_PIN K3 [get_ports {Segment[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[4]}]
set_property PACKAGE_PIN M2 [get_ports {Segment[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[5]}]
set_property PACKAGE_PIN L6 [get_ports {Segment[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Segment[6]}]
set_property PACKAGE_PIN M4 [get_ports Segment[7]]							
	set_property IOSTANDARD LVCMOS33 [get_ports Segment[7]]

set_property PACKAGE_PIN N6 [get_ports {Anod[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[0]}]
set_property PACKAGE_PIN M6 [get_ports {Anod[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[1]}]
set_property PACKAGE_PIN M3 [get_ports {Anod[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[2]}]
set_property PACKAGE_PIN N5 [get_ports {Anod[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[3]}]
set_property PACKAGE_PIN N2 [get_ports {Anod[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[4]}]
set_property PACKAGE_PIN N4 [get_ports {Anod[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[5]}]
set_property PACKAGE_PIN L1 [get_ports {Anod[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[6]}]
set_property PACKAGE_PIN M1 [get_ports {Anod[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Anod[7]}]

##Buttons
set_property PACKAGE_PIN C12 [get_ports Reset]				
	set_property IOSTANDARD LVCMOS33 [get_ports Reset]

##Pmod Header JA
set_property PACKAGE_PIN B13 [get_ports {JA[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[0]}]
set_property PACKAGE_PIN F14 [get_ports {JA[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[1]}]
set_property PACKAGE_PIN D17 [get_ports {JA[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[2]}]
set_property PACKAGE_PIN E17 [get_ports {JA[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[3]}]
set_property PACKAGE_PIN G13 [get_ports {JA[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[4]}]
set_property PACKAGE_PIN C17 [get_ports {JA[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[5]}]
set_property PACKAGE_PIN D18 [get_ports {JA[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[6]}]
set_property PACKAGE_PIN E18 [get_ports {JA[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JA[7]}]

##Pmod Header JB
set_property PACKAGE_PIN K16 [get_ports {JB[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JB[4]}]
set_property PACKAGE_PIN R16 [get_ports {JB[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JB[5]}]
set_property PACKAGE_PIN T9 [get_ports {JB[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JB[6]}]
set_property PACKAGE_PIN U11 [get_ports {JB[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {JB[7]}]	